### ISSUE TITLE
What is the impact of `klee-analysis` : you forgot to answer this one.

### ISSUE THREAD

**Issue by glydzo** [HectorNyblom/d7020e_lab1#6]
Have a look to that :

https://gitlab.henriktjader.com/KLEE/klee-sys/-/blob/master/src/lib.rs#L19-25

https://github.com/HectorNyblom/d7020e_lab1/blob/86eccf11670326756582f1d2858c9f44dab33ddb/cargo_klee_examples/examples/get_sign.rs#L92-L95

**Comment by HectorNyblom** [comment]
its answered now
